// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewReview struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Query struct {
}

type Review struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  *User  `json:"author"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
