// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews"`
}

func (Movie) IsEntity() {}

type Mutation struct {
}

type NewReview struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Query struct {
}

type Review struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (Review) IsEntity() {}
