services:
  movies:
    build:
      context: ./movies
      dockerfile: Dockerfile
    environment:
      - PORT=5001
    ports:
      - "${PORT}:5001"

  reviews:
    build:
      context: ./reviews
      dockerfile: Dockerfile
    environment:
      - PORT=5002
    ports:
      - "${PORT}:5002"
