package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/Krysik/gql-federation-demo/domain"
	"github.com/Krysik/gql-federation-demo/graph/model"
)

// FindMovieByID is the resolver for the findMovieByID field.
func (r *entityResolver) FindMovieByID(ctx context.Context, id string) (*model.Movie, error) {
	reviews, err := domain.FindReviewsByMovieId(id)

	if err != nil {
		return nil, err
	}

	return &model.Movie{
		ID:      "1-movie",
		Reviews: reviews,
	}, nil
}

// FindReviewByID is the resolver for the findReviewByID field.
func (r *entityResolver) FindReviewByID(ctx context.Context, id string) (*model.Review, error) {
	review, err := domain.FindReviewById(id)

	if err != nil {
		return nil, err
	}

	return review, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
