package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/Krysik/gql-federation-demo/graph/model"
)

var reviews []*model.Review = []*model.Review{
	&model.Review{
		ID:      "id-1",
		Title:   "Title 1",
		Content: "Content 1",
		Author: &model.User{
			ID:   "usr-1",
			Name: "John",
		},
	},
}

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model.NewReview) (*model.Review, error) {
	review := model.Review{
		ID:      "id-2",
		Title:   input.Title,
		Content: input.Content,
		Author:  &model.User{ID: "usr-2", Name: "Jane"},
	}

	reviews = append(reviews, &review)

	return &review, nil
}

// Reviews is the resolver for the reviews field.
func (r *queryResolver) Reviews(ctx context.Context) ([]*model.Review, error) {
	return reviews, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
